# Generated by Django 3.1 on 2020-09-04 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bakery_name', models.CharField(max_length=50)),
                ('Bakery_address', models.CharField(max_length=100)),
                ('Bakery_menu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bakery_Location',
            fields=[
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='page.bakery_info')),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bakery_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bakery_Reviewer', models.CharField(max_length=50)),
                ('Bakery_Contents', models.TextField()),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.bakery_info')),
            ],
        ),
    ]
